// Package autocert renders compose.override.yml from a project's
// https_entrypoint field. This is how flotilla generates Traefik labels
// without touching the user's compose.yml in git.
//
// See docs/ARCHITECTURE.md §3.2 («Container labels») and §5 step 0.
//
// The generated override is written to .flotilla/compose.override.yml
// (or kept in memory in --dry mode). On every deploy it is rewritten
// from scratch.
package autocert

import (
	"errors"
	"fmt"

	"github.com/DmitriyKurilenko/flotilla/internal/compose"
	"github.com/DmitriyKurilenko/flotilla/internal/project"
	"gopkg.in/yaml.v3"
)

// ErrNoEntrypoint is returned by Render when the project has no
// https_entrypoint. Callers must check Project.HTTPSEntrypoint != nil
// before invoking Render; this error is a guard, not a normal path.
var ErrNoEntrypoint = errors.New("autocert: project has no https_entrypoint")

// Render produces the YAML bytes of compose.override.yml that wire up
// Traefik labels for proj.HTTPSEntrypoint.
//
// The generated override:
//   - enables Traefik on the target service,
//   - attaches it to the external `proxy` network,
//   - declares a single websecure router Host(`<domain>`) with the `le`
//     cert resolver,
//   - points the loadbalancer at the resolved container port.
//
// Router/service name = proj.RouterName() (underscores → hyphens).
//
// Errors:
//   - ErrNoEntrypoint if proj.HTTPSEntrypoint is nil
//   - the named service does not exist in comp
//   - the port cannot be inferred and proj.HTTPSEntrypoint.Port is 0
func Render(proj *project.File, comp *compose.File) ([]byte, error) {
	if proj == nil || proj.HTTPSEntrypoint == nil {
		return nil, ErrNoEntrypoint
	}
	if comp == nil {
		return nil, errors.New("autocert: nil compose file")
	}

	svcName := proj.HTTPSEntrypoint.Service
	svc, ok := comp.Services[svcName]
	if !ok {
		return nil, fmt.Errorf("autocert: https_entrypoint service %q not found in compose", svcName)
	}

	port := proj.HTTPSEntrypoint.Port
	if port == 0 {
		inferred, err := InferPort(svc)
		if err != nil {
			return nil, fmt.Errorf("autocert: %w", err)
		}
		port = inferred
	}

	router := proj.RouterName()
	domain := proj.Domain

	labels := []string{
		"traefik.enable=true",
		"traefik.docker.network=proxy",
		fmt.Sprintf("traefik.http.routers.%s.rule=Host(`%s`)", router, domain),
		fmt.Sprintf("traefik.http.routers.%s.entrypoints=websecure", router),
		fmt.Sprintf("traefik.http.routers.%s.tls=true", router),
		fmt.Sprintf("traefik.http.routers.%s.tls.certresolver=le", router),
		fmt.Sprintf("traefik.http.routers.%s.service=%s", router, router),
		fmt.Sprintf("traefik.http.services.%s.loadbalancer.server.port=%d", router, port),
	}

	// Build the override document. We use yaml.Marshal on a typed
	// structure so the output is deterministic and correctly escaped.
	override := overrideDoc{
		Services: map[string]overrideService{
			svcName: {
				Labels:   labels,
				Networks: []string{"proxy"},
			},
		},
		Networks: map[string]overrideNetwork{
			"proxy": {External: true, Name: "proxy"},
		},
	}

	out, err := yaml.Marshal(override)
	if err != nil {
		return nil, fmt.Errorf("autocert: marshal override: %w", err)
	}

	header := "" +
		"# Generated by flotilla. DO NOT EDIT.\n" +
		"# Source: project.yml https_entrypoint → service " + svcName + "\n" +
		"# Rewritten on every `flotilla deploy`. Safe to delete.\n"
	return append([]byte(header), out...), nil
}

// overrideDoc is the minimal compose document flotilla emits as the
// autocert override. Only the fields we set are present, so the merge
// with the user's compose.yml is additive.
type overrideDoc struct {
	Services map[string]overrideService `yaml:"services"`
	Networks map[string]overrideNetwork `yaml:"networks"`
}

type overrideService struct {
	Labels   []string `yaml:"labels"`
	Networks []string `yaml:"networks"`
}

type overrideNetwork struct {
	External bool   `yaml:"external"`
	Name     string `yaml:"name"`
}

// InferPort returns the port flotilla will route to for svc. Rules, in
// priority order:
//
//   - exactly one entry in svc.Expose → use it.
//   - exactly one published port in svc.Ports → use its Target.
//   - otherwise → error; caller must supply an explicit port via the
//     object form of https_entrypoint.
//
// Rationale: `expose:` is the unambiguous «this is the app port»
// declaration. `ports:` may publish multiple host mappings; we only
// auto-pick when there is exactly one.
func InferPort(svc compose.Service) (int, error) {
	if len(svc.Expose) == 1 {
		return svc.Expose[0], nil
	}
	if len(svc.Expose) > 1 {
		return 0, fmt.Errorf("service %q exposes %d ports; set https_entrypoint.port explicitly", svc.Name, len(svc.Expose))
	}

	var targets []int
	seen := map[int]struct{}{}
	for _, p := range svc.Ports {
		if p.Target == 0 {
			continue
		}
		if _, dup := seen[p.Target]; dup {
			continue
		}
		seen[p.Target] = struct{}{}
		targets = append(targets, p.Target)
	}
	switch len(targets) {
	case 1:
		return targets[0], nil
	case 0:
		return 0, fmt.Errorf("service %q declares no expose/ports; set https_entrypoint.port explicitly", svc.Name)
	default:
		return 0, fmt.Errorf("service %q publishes %d distinct container ports; set https_entrypoint.port explicitly", svc.Name, len(targets))
	}
}
