package autocert

import (
	"strings"
	"testing"

	"github.com/DmitriyKurilenko/flotilla/internal/compose"
	"github.com/DmitriyKurilenko/flotilla/internal/project"
	"gopkg.in/yaml.v3"
)

func TestRender_ShortcutInferFromExpose(t *testing.T) {
	proj := &project.File{
		Name:            "crm_prvms",
		Domain:          "crm.prvms.ru",
		HTTPSEntrypoint: &project.HTTPSEntrypoint{Service: "web"}, // no port → infer
	}
	comp := &compose.File{Services: map[string]compose.Service{
		"web": {Name: "web", Expose: []int{8000}},
	}}

	out, err := Render(proj, comp)
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	s := string(out)

	// Header present.
	if !strings.Contains(s, "Generated by flotilla. DO NOT EDIT.") {
		t.Errorf("missing generated header:\n%s", s)
	}

	// Round-trip the YAML to assert structure rather than string-match.
	var doc struct {
		Services map[string]struct {
			Labels   []string `yaml:"labels"`
			Networks []string `yaml:"networks"`
		} `yaml:"services"`
		Networks map[string]struct {
			External bool   `yaml:"external"`
			Name     string `yaml:"name"`
		} `yaml:"networks"`
	}
	if err := yaml.Unmarshal(out, &doc); err != nil {
		t.Fatalf("override is not valid YAML: %v\n%s", err, s)
	}
	web, ok := doc.Services["web"]
	if !ok {
		t.Fatalf("override missing service web:\n%s", s)
	}
	wantLabels := map[string]bool{
		"traefik.enable=true":                                           true,
		"traefik.docker.network=proxy":                                  true,
		"traefik.http.routers.crm-prvms.rule=Host(`crm.prvms.ru`)":      true,
		"traefik.http.routers.crm-prvms.entrypoints=websecure":          true,
		"traefik.http.routers.crm-prvms.tls=true":                       true,
		"traefik.http.routers.crm-prvms.tls.certresolver=le":            true,
		"traefik.http.routers.crm-prvms.service=crm-prvms":              true,
		"traefik.http.services.crm-prvms.loadbalancer.server.port=8000": true,
	}
	for _, l := range web.Labels {
		delete(wantLabels, l)
	}
	if len(wantLabels) != 0 {
		t.Errorf("missing expected labels: %v\ngot: %v", wantLabels, web.Labels)
	}
	if len(web.Networks) != 1 || web.Networks[0] != "proxy" {
		t.Errorf("web.Networks = %v, want [proxy]", web.Networks)
	}
	if n, ok := doc.Networks["proxy"]; !ok || !n.External || n.Name != "proxy" {
		t.Errorf("networks.proxy = %+v, want {external:true name:proxy}", n)
	}
}

func TestRender_ExplicitPortOverridesInference(t *testing.T) {
	proj := &project.File{
		Name:            "app",
		Domain:          "app.example.com",
		HTTPSEntrypoint: &project.HTTPSEntrypoint{Service: "web", Port: 9000},
	}
	comp := &compose.File{Services: map[string]compose.Service{
		"web": {Name: "web", Expose: []int{8000}}, // would infer 8000, but explicit 9000 wins
	}}
	out, err := Render(proj, comp)
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if !strings.Contains(string(out), "loadbalancer.server.port=9000") {
		t.Errorf("explicit port 9000 not used:\n%s", out)
	}
}

func TestRender_Errors(t *testing.T) {
	tests := []struct {
		name string
		proj *project.File
		comp *compose.File
	}{
		{
			name: "no entrypoint",
			proj: &project.File{Name: "x", Domain: "x.example.com"},
			comp: &compose.File{},
		},
		{
			name: "service missing",
			proj: &project.File{Name: "x", Domain: "x.example.com", HTTPSEntrypoint: &project.HTTPSEntrypoint{Service: "ghost"}},
			comp: &compose.File{Services: map[string]compose.Service{"web": {Name: "web", Expose: []int{80}}}},
		},
		{
			name: "port not inferable",
			proj: &project.File{Name: "x", Domain: "x.example.com", HTTPSEntrypoint: &project.HTTPSEntrypoint{Service: "web"}},
			comp: &compose.File{Services: map[string]compose.Service{"web": {Name: "web"}}}, // no expose/ports
		},
		{
			name: "nil compose",
			proj: &project.File{Name: "x", Domain: "x.example.com", HTTPSEntrypoint: &project.HTTPSEntrypoint{Service: "web"}},
			comp: nil,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if _, err := Render(tt.proj, tt.comp); err == nil {
				t.Errorf("expected error, got nil")
			}
		})
	}
}

func TestInferPort(t *testing.T) {
	tests := []struct {
		name    string
		svc     compose.Service
		want    int
		wantErr bool
	}{
		{"single expose", compose.Service{Name: "s", Expose: []int{8000}}, 8000, false},
		{"multi expose", compose.Service{Name: "s", Expose: []int{8000, 9000}}, 0, true},
		{"single port", compose.Service{Name: "s", Ports: []compose.Port{{Target: 80, Host: 8080}}}, 80, false},
		{"duplicate target collapses to one", compose.Service{Name: "s", Ports: []compose.Port{{Target: 80, Host: 80}, {Target: 80, Host: 8080}}}, 80, false},
		{"multi distinct ports", compose.Service{Name: "s", Ports: []compose.Port{{Target: 80}, {Target: 443}}}, 0, true},
		{"nothing", compose.Service{Name: "s"}, 0, true},
		{"expose wins over ports", compose.Service{Name: "s", Expose: []int{8000}, Ports: []compose.Port{{Target: 80}, {Target: 443}}}, 8000, false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := InferPort(tt.svc)
			if tt.wantErr {
				if err == nil {
					t.Errorf("want error, got port %d", got)
				}
				return
			}
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if got != tt.want {
				t.Errorf("InferPort = %d, want %d", got, tt.want)
			}
		})
	}
}
